name: Extract and Commit

on:
  push:
    branches:
      - main

jobs:
  extract_and_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Extract ZIP file
      run: unzip path/to/assets.zip -d extracted-files
      
    - name: Add Changes
      run: git add .

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Extracted and added contents of ZIP file"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
