name: Extract Zip File

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  extract_zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Extract Zip
      run: unzip assets.zip
